# ================================
# FILE: docker-compose.yml
# ================================

version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: chatbot_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PSQL_USERNAME=postgres
      - PSQL_PASSWORD=your_password
      - PSQL_HOST=db
      - PSQL_PORT=5432
      - PSQL_DATABASE=chatbot_db
      - PSQL_SSLMODE=disable
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
